//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFConnectWithChrist
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int UserID { get; set; }
        public string Firstname { get; set; }
        public string Lastname { get; set; }
        public string email { get; set; }
        public string password { get; set; }
        public string phoneNumber { get; set; }
        public int mainBusinessID { get; set; }
        public System.DateTime dayAndTimeJoined { get; set; }
        public int UserType { get; set; }
    
        public virtual MainBusiness MainBusiness { get; set; }
        public virtual UserType UserType1 { get; set; }
    }
}
